spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.104.227.161:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.227.161:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10000
logging:
  level:
    com.lizhimin.gulimall: debug