spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.227.161:8848
    alicloud:
      access-key: LTAI4G3CGgkXifc7EZqpZbTH
      secret-key: vQIKXPzkpsVTGeyUopsaBhpaa43ud0
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: gulimall-third-party


server:
  port: 11000

logging:
  level:
    com.lizhimin.gulimall: debug
